
server:
  port: 1100


#Database
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: Password123@
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # for h2 console
  h2:
    console:
      enabled: true
      path: /h2-console

