
server:
  port: ${PROJECT_HOST_PORT:1100}


#Database
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: Password123@
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # for h2 console
  h2:
    console:
      enabled: true
      path: /h2-console


springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true

project:
  openapi:
    dev-url: "${PROJECT_HOST_DEV:http://127.0.0.1}:${PROJECT_HOST_PORT:1100}"
    prod-url: "${PROJECT_HOST_PRO:http://127.0.0.1}:${PROJECT_HOST_PORT:1100}"


uni-pos:
  middleware:
    host: ${UMEE_MIDDLEWARE_HOST:https://api-staging.kienlongbank.co/pay-middleware}
    key: ${UMEE_MIDDLEWARE_KEY:49E001F9169ACA8270EE6138342B4FD7}
    client-id: ${UMEE_MIDDLEWARE_CLIENT_ID:838e919b-ce19-43bf-b338-75adbe045726}
    secret-key: ${UMEE_MIDDLEWARE_SIGNATURE_KEY:6EB00D84532E5006CF86A237DE038D9A}
    encrypt-key: ${UMEE_MIDDLEWARE_ENCRYPT_KEY:6EB00D84532E5006CF86A237DE038D9A}
    accept-time-diff: ${MAX_TIMESTAMP_DIFF_MS:30000}
  bin-default: ${UNI_POS_BIN_BANK_DEFAULT:970452}
  paygate:
    prefix: ${PAGE_PREFIX:1012}
    client-id: ${PAYGATE_CLIENT_ID:3023e466-52d6-49c4-9b32-b574bd3ff3e9}
    encrypt-key: ${PAYGATE_ENCRYPT_KEY:CA39DA45427076B3D8B7286622273FD2B4F2A401E892E1B1DE19B84332D948F1}
    signature-key: ${PAYGATE_SIGNATURE_KEY:2E1B39AE4C3EA598AE76DE111678294B}
    accept-time-diff: ${PAYGATE_TIMESTAMP_DIFF_MS:30000}
    timeout: ${PAYGATE_TIMEOUT:300}
    bin: ${PAYGATE_BIN:970452}
